server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .jsp

