drop table if exists categories CASCADE;
drop table if exists categories_products CASCADE;
drop table if exists products CASCADE;
drop table if exists roles CASCADE;
drop table if exists users CASCADE;
drop table if exists users_roles CASCADE;
drop sequence if exists hibernate_sequence;

create sequence hibernate_sequence start with 1 increment by 1;

create table categories (id bigint generated by default as identity, name varchar(255) not null, primary key (id));

create table categories_products (product_id bigint not null, category_id bigint not null);

create table products (id bigint not null, name varchar(255) not null, primary key (id));

create table roles (id BIGSERIAL, role_name varchar(255), primary key (id));

create table users (id BIGSERIAL, email varchar(255), first_name varchar(255),
                    last_name varchar(255), password varchar(255), username varchar(255), primary key (id));

create table users_roles (user_id bigint not null, role_id bigint not null);

alter table categories_products add constraint FK2a3u5mbtmtq3d4s5abajhhksf foreign key (category_id) references categories;

alter table categories_products add constraint FK2tnk948b1lgpg3uggwyi2kwfq foreign key (product_id) references products;

alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;

alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;

insert into roles (role_name) values ('ADMIN'), ('CUSTOMER');

insert into users (username, password) values ('user1', '123'), ('user2', '123');
insert into users_roles (user_id, role_id) values (1, 1), (2, 2);